server:
  port: 8085
car:
  types:
    MERS:
      name: MERS car
      age: 20
      color: black
    AUDI:
      name: AUDI car
      age: 5
      color: WHITE
    HONDA:
      name: HONDA car
      age: 10
      color: RED

file:
  create-path:
    name: dev